#!/system/bin/sh

VOLTAGE=-60mV

#governor tweak
/system/bin/insmod /system/lib/modules/cpufreq_hotplug.ko
/system/bin/insmod /system/lib/modules/cpufreq_intellidemand.ko
/system/bin/insmod /system/lib/modules/cpufreq_interactive.ko
/system/bin/insmod /system/lib/modules/cpufreq_lagfree.ko
/system/bin/insmod /system/lib/modules/cpufreq_lazy.ko
/system/bin/insmod /system/lib/modules/cpufreq_lionheart.ko
/system/bin/insmod /system/lib/modules/cpufreq_minmax.ko
/system/bin/insmod /system/lib/modules/cpufreq_ondemandx.ko

OLDGOV=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 312000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 832000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo $OLDGOV > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo $VOLTAGE > /proc/sys/bacem/volt/cpu

#io tweak
/system/bin/insmod /system/lib/modules/vr-iosched.ko

