#!/system/bin/sh

#governor tweak
insmod /system/lib/modules/cpufreq_hotplug.ko
insmod /system/lib/modules/cpufreq_intellidemand.ko
insmod /system/lib/modules/cpufreq_interactive.ko
insmod /system/lib/modules/cpufreq_lagfree.ko
insmod /system/lib/modules/cpufreq_lazy.ko
insmod /system/lib/modules/cpufreq_lionheart.ko
insmod /system/lib/modules/cpufreq_minmax.ko
insmod /system/lib/modules/cpufreq_ondemandx.ko

echo "bcm21553" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "312000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "832000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq


#io tweak
/system/bin/insmod /system/lib/modules/vr-iosched.ko

echo "noop" > /sys/block/stl1/queue/scheduler
echo "noop" > /sys/block/stl2/queue/scheduler
echo "noop" > /sys/block/stl3/queue/scheduler
echo "noop" > /sys/block/stl4/queue/scheduler
echo "noop" > /sys/block/stl5/queue/scheduler
echo "noop" > /sys/block/stl6/queue/scheduler
echo "noop" > /sys/block/stl7/queue/scheduler
echo "noop" > /sys/block/stl8/queue/scheduler
echo "noop" > /sys/block/stl9/queue/scheduler
echo "noop" > /sys/block/stl10/queue/scheduler
echo "noop" > /sys/block/stl11/queue/scheduler
echo "noop" > /sys/block/stl12/queue/scheduler
echo "noop" > /sys/block/stl13/queue/scheduler
echo "noop" > /sys/block/stl14/queue/scheduler
echo "noop" > /sys/block/stl15/queue/scheduler

echo "noop" > /sys/block/bml1/queue/scheduler
echo "noop" > /sys/block/bml2/queue/scheduler
echo "noop" > /sys/block/bml3/queue/scheduler
echo "noop" > /sys/block/bml4/queue/scheduler
echo "noop" > /sys/block/bml5/queue/scheduler
echo "noop" > /sys/block/bml6/queue/scheduler
echo "noop" > /sys/block/bml7/queue/scheduler
echo "noop" > /sys/block/bml8/queue/scheduler
echo "noop" > /sys/block/bml9/queue/scheduler
echo "noop" > /sys/block/bml10/queue/scheduler
echo "noop" > /sys/block/bml11/queue/scheduler
echo "noop" > /sys/block/bml12/queue/scheduler
echo "noop" > /sys/block/bml13/queue/scheduler
echo "noop" > /sys/block/bml14/queue/scheduler
echo "noop" > /sys/block/bml15/queue/scheduler

echo "noop" > /sys/block/mmcblk0/queue/scheduler
echo "1024" > /sys/block/mmcblk0/queue/read_ahead_kb